nodeLinker: node-modules
packageExtensions:
  '@vue/eslint-config-typescript@*':
    peerDependencies:
      '@typescript-eslint/parser': '*'
  'netlify-cli@*':
    peerDependencies:
      '@types/node': '*'
  '@netlify/build@*':
    peerDependencies:
      '@types/node': '*'
