nodeLinker: node-modules

packageExtensions:
  "@netlify/build@*":
    peerDependencies:
      "@types/node": "*"
  "@vue/eslint-config-typescript@*":
    peerDependencies:
      "@typescript-eslint/parser": "*"
  netlify-cli@*:
    peerDependencies:
      "@types/node": "*"
