[build]
# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[dev]
  command = "yarn quasar dev -T chrome"
  targetPort = 9000
  port = 8888
  publish = "dist/spa"
